export function spmtSharedUiHead(appId: string): string {
  const safeApp = JSON.stringify(appId).slice(1, -1);
  return `<style id="spmt-shared-shell-style">
:root{--spmt-bg:#080b14;--spmt-surface:#171321;--spmt-surface-rgb:23,19,33;--spmt-text:#f8fafc;--spmt-accent:#ff8a3d;--spmt-accent-rgb:255,138,61;--spmt-radius:18px;--spmt-glass:.65;--spmt-blur:22px;--spmt-border:.15;--spmt-stars:.7;--spmt-nebula:.8;--spmt-glow:.8;--spmt-density:1;--spmt-motion:1}
html[data-spmt-theme]{background:var(--spmt-bg);color:var(--spmt-text)}
body.spmt-host-shell{background:var(--spmt-bg)!important;color:var(--spmt-text)!important;position:relative;isolation:isolate;padding-bottom:76px!important}
.spmt-star-layer{position:fixed;inset:0;z-index:-2;pointer-events:none;overflow:hidden;opacity:var(--spmt-stars)}
.spmt-star{position:absolute;width:2px;height:2px;border-radius:999px;background:#fff;box-shadow:0 0 5px rgba(255,255,255,.65)}
body.spmt-host-shell:after{content:"";position:fixed;inset:0;pointer-events:none;z-index:-1;background:radial-gradient(circle at 10% 0%,rgba(var(--spmt-accent-rgb),calc(.25 * var(--spmt-nebula))),transparent 36rem),radial-gradient(circle at 92% 86%,rgba(var(--spmt-accent-rgb),calc(.12 * var(--spmt-nebula))),transparent 34rem),linear-gradient(180deg,var(--spmt-bg),#03050a 92%)}
body.spmt-host-shell :is(.panel,.card,.hero,.status,.topbar,.toolbar,.workspace-card,.surface,.box){border-color:rgba(255,255,255,var(--spmt-border))!important;border-radius:var(--spmt-radius)!important;backdrop-filter:blur(var(--spmt-blur))!important;-webkit-backdrop-filter:blur(var(--spmt-blur))!important}
body.spmt-host-shell :is(.panel,.card,.hero,.status,.workspace-card,.surface,.box){background:rgba(var(--spmt-surface-rgb),calc(var(--spmt-glass) * .72))!important}
body.spmt-host-shell :is(.button.primary,button:not(.secondary):not(.ghost),.primary){background:linear-gradient(135deg,var(--spmt-accent),rgba(var(--spmt-accent-rgb),.62))!important}
body.spmt-host-shell .eyebrow{color:var(--spmt-accent)!important}
body.spmt-host-shell .shell{padding-top:calc(24px * var(--spmt-density))!important}
body.spmt-host-shell.spmt-no-motion *,body.spmt-host-shell.spmt-no-motion *:before,body.spmt-host-shell.spmt-no-motion *:after{scroll-behavior:auto!important;transition:none!important;animation:none!important}
.spmt-runtime-overlay{position:fixed;inset:0;z-index:10010;pointer-events:none;overflow:hidden}.spmt-runtime-overlay iframe{position:absolute;inset:0;width:100%;height:100%;border:0;background:transparent;pointer-events:none}
.spmt-workspace-panel{position:fixed;left:50%;bottom:84px;transform:translateX(-50%);z-index:10030;width:min(980px,calc(100vw - 36px));height:min(72vh,700px);display:grid;grid-template-rows:auto minmax(0,1fr);overflow:hidden;border:1px solid rgba(255,255,255,.15);border-radius:calc(var(--spmt-radius) + 4px);background:rgba(3,5,10,.92);box-shadow:0 28px 90px rgba(0,0,0,.62);backdrop-filter:blur(24px)}
.spmt-workspace-panel[hidden]{display:none!important}.spmt-workspace-bar{display:flex;align-items:center;gap:8px;padding:9px;border-bottom:1px solid rgba(255,255,255,.1);background:rgba(255,255,255,.025)}.spmt-workspace-tabs{display:flex;min-width:0;flex:1;gap:7px;flex-wrap:wrap}.spmt-workspace-tabs button,.spmt-workspace-close{display:inline-flex;align-items:center;gap:7px;border:1px solid rgba(255,255,255,.1);border-radius:10px;padding:8px 10px;background:rgba(255,255,255,.035);color:#d4d4d8;font:750 12px Inter,ui-sans-serif,system-ui,sans-serif;cursor:pointer}.spmt-workspace-tabs button.active{border-color:rgba(var(--spmt-accent-rgb),.62);background:rgba(var(--spmt-accent-rgb),.14);color:#fff}.spmt-workspace-close{margin-left:auto}.spmt-workspace-frame{width:100%;height:100%;border:0;background:transparent}.spmt-workspace-empty{display:grid;place-items:center;padding:28px;text-align:center;color:#a1a1aa;font:600 13px/1.5 Inter,ui-sans-serif,system-ui,sans-serif}
.spmt-workspace-tray{position:fixed;left:50%;bottom:12px;transform:translateX(-50%);z-index:10040;width:min(980px,calc(100vw - 36px));display:flex;align-items:center;gap:8px;min-height:58px;padding:8px;border:1px solid rgba(255,255,255,.15);border-radius:calc(var(--spmt-radius) + 2px);background:rgba(3,5,10,.82);box-shadow:0 -14px 42px rgba(0,0,0,.45),0 0 calc(28px * var(--spmt-glow)) rgba(var(--spmt-accent-rgb),.12);backdrop-filter:blur(20px)}
.spmt-workspace-main,.spmt-slot,.spmt-manage button{border:1px solid rgba(255,255,255,.1);background:rgba(255,255,255,.035);color:#fff;border-radius:11px;cursor:pointer;font-family:Inter,ui-sans-serif,system-ui,sans-serif}.spmt-workspace-main{display:inline-flex;align-items:center;gap:8px;min-height:40px;padding:0 12px;font-size:12px;font-weight:800}.spmt-workspace-main svg,.spmt-manage svg{width:16px;height:16px;fill:none;stroke:currentColor;stroke-width:1.8;stroke-linecap:round;stroke-linejoin:round}.spmt-status-dot{width:7px;height:7px;border-radius:999px;background:#fbbf24}.spmt-status-dot.connected{background:#34d399}.spmt-slots{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:7px;min-width:0;flex:1}.spmt-slot{min-width:0;padding:7px 10px;text-align:left}.spmt-slot strong,.spmt-slot small{display:block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.spmt-slot strong{font-size:11px}.spmt-slot small{margin-top:3px;color:#71717a;font-size:9px;text-transform:uppercase;letter-spacing:.08em}.spmt-slot.active{border-color:rgba(var(--spmt-accent-rgb),.55);background:rgba(var(--spmt-accent-rgb),.12)}.spmt-manage{display:flex;gap:5px}.spmt-manage button{display:grid;place-items:center;min-width:38px;height:38px;padding:0 8px;color:#d4d4d8}.spmt-manage button:hover{color:#fff;background:rgba(255,255,255,.08)}.spmt-personal-toggle{font-size:9px!important;font-weight:800!important;white-space:nowrap}
@media(max-width:720px){body.spmt-host-shell{padding-bottom:70px!important}.spmt-workspace-panel{inset:10px 10px 78px 10px;transform:none;width:auto;height:auto}.spmt-workspace-tray{bottom:8px;width:calc(100vw - 16px)}.spmt-workspace-main span.label,.spmt-manage{display:none}.spmt-slot{padding:7px}.spmt-slot small{display:none}}
@media(prefers-reduced-motion:reduce){body.spmt-host-shell *,body.spmt-host-shell *:before,body.spmt-host-shell *:after{scroll-behavior:auto!important;transition:none!important;animation:none!important}}
</style><meta name="spmt-host-app" content="${safeApp}">`;
}

export function spmtSharedUiScript(appId: string, profileEndpoint = "/athena/api/settings"): string {
  const encodedApp = JSON.stringify(appId);
  const encodedProfileEndpoint = JSON.stringify(profileEndpoint);
  return `<script id="spmt-shared-shell-script">
(()=>{
  const APP=${encodedApp};
  const PROFILE_ENDPOINT=${encodedProfileEndpoint};
  const EMBEDDED=window.self!==window.top;
  if(EMBEDDED)return;
  const VISIBILITY_KEY='spmt:'+APP+':personal-overlay-visible';
  const palettes={
    'solar-flare':{bg:'#080b14',surface:'#171321',text:'#f8fafc',accent:'#ff8a3d'},
    'nebula-purple':{bg:'#090712',surface:'#1d1530',text:'#f8f4ff',accent:'#a855f7'},
    'oceanic-blue':{bg:'#06111a',surface:'#0c2535',text:'#effaff',accent:'#22d3ee'},
    'aurora-green':{bg:'#07110d',surface:'#10291e',text:'#f0fdf4',accent:'#34d399'}
  };
  const root=document.documentElement;
  const state={connected:false,profile:null,origin:'',surfaces:[],outputs:{public:'',personal:''},personalOverlayUrl:'',personalVisible:true,activeKind:'surface',activeId:'worktray'};
  let starLayer=null,tray=null,panel=null,frame=null,empty=null,overlayLayer=null;
  document.body.classList.add('spmt-host-shell');
  try{state.personalVisible=localStorage.getItem(VISIBILITY_KEY)!=='0'}catch{}
  function rgb(hex){const v=String(hex||'').replace('#','');if(!/^[0-9a-f]{6}$/i.test(v))return'255,138,61';return parseInt(v.slice(0,2),16)+','+parseInt(v.slice(2,4),16)+','+parseInt(v.slice(4,6),16)}
  function radius(v){return({sm:'12px',md:'18px',lg:'26px',full:'999px'})[v]||'18px'}
  function profileFrom(data){return data&&data.shared&&data.shared.profile||data&&data.workspace&&data.workspace.profile||data&&data.profile||null}
  function canonicalFrom(data){return data&&data.shared&&data.shared.canonical||data&&data.canonical||{}}
  function apply(profile){
    const a=profile&&profile.appearance;if(!a)return;
    const mapping=String((profile.appThemeMappings||{})[APP]||'follow-workspace');
    const themeId=mapping==='follow-workspace'?a.themeId:mapping;
    const p=palettes[themeId]||palettes['solar-flare'];
    const accent=a.accentColor||p.accent;
    root.dataset.spmtTheme=themeId;
    root.style.setProperty('--spmt-bg',p.bg);root.style.setProperty('--spmt-surface',p.surface);root.style.setProperty('--spmt-surface-rgb',rgb(p.surface));root.style.setProperty('--spmt-text',p.text);root.style.setProperty('--spmt-accent',accent);root.style.setProperty('--spmt-accent-rgb',rgb(accent));
    root.style.setProperty('--spmt-radius',radius(a.cornerRadius));root.style.setProperty('--spmt-glass',String((a.glassOpacity??65)/100));root.style.setProperty('--spmt-blur',String(a.blurStrength??22)+'px');root.style.setProperty('--spmt-border',String(Math.max(.06,(a.borderStrength??60)/400)));root.style.setProperty('--spmt-stars',String((a.starDensity??70)/100));root.style.setProperty('--spmt-nebula',String((a.nebulaIntensity??80)/100));root.style.setProperty('--spmt-glow',String((a.glowIntensity??80)/100));root.style.setProperty('--spmt-density',a.density==='compact'?'.86':a.density==='spacious'?'1.15':'1');
    document.body.classList.toggle('spmt-no-motion',a.animation&&a.animation.enabled===false||a.accessibility&&a.accessibility.reduceMotion===true);
    renderStars(Number(a.starDensity??70));
  }
  function icon(kind){return kind==='settings'?'<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="3"/><path d="M19 13.5v-3l-2-.6a7 7 0 0 0-.7-1.7l1-1.8-2.1-2.1-1.8 1a7 7 0 0 0-1.7-.7L11 2H8l-.6 2a7 7 0 0 0-1.7.7l-1.8-1L1.8 5.8l1 1.8a7 7 0 0 0-.7 1.7L0 10v3l2 .6a7 7 0 0 0 .7 1.7l-1 1.8 2.1 2.1 1.8-1a7 7 0 0 0 1.7.7L8 21h3l.6-2a7 7 0 0 0 1.7-.7l1.8 1 2.1-2.1-1-1.8a7 7 0 0 0 .7-1.7z"/></svg>':kind==='overlay'?'<svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="3"/><path d="M8 8h8v8H8z"/></svg>':'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 5h16v4H4zM4 11h7v8H4zM13 11h7v8h-7z"/></svg>'}
  function renderStars(density){if(!starLayer)return;starLayer.innerHTML='';const count=Math.max(8,Math.min(90,Math.round(Number(density||70)*.75)));for(let i=0;i<count;i+=1){const star=document.createElement('i');star.className='spmt-star';star.style.left=String((i*73+17)%997/10)+'%';star.style.top=String((i*131+29)%991/10)+'%';const size=1+((i*17)%3);star.style.width=size+'px';star.style.height=size+'px';star.style.opacity=String(.32+((i*31)%60)/100);starLayer.append(star)}}
  function slots(){const raw=Array.isArray(state.profile&&state.profile.dockSlots)?state.profile.dockSlots:[];return[1,2,3].map(id=>raw.find(s=>Number(s&&s.id)===id)||{id:id,title:'Slot '+id,url:'',collapsed:true})}
  function surface(id){return(Array.isArray(state.surfaces)?state.surfaces:[]).find(s=>String(s&&s.id||'')===id)||null}
  function surfaceUrl(id){const item=surface(id);const raw=String(item&&item.url||item&&item.path||'').trim();if(!raw)return'';try{const url=new URL(raw,state.origin||location.origin);url.searchParams.set('app',APP);url.searchParams.set('mode',id==='worktray'?'panel':'full');if(id==='overlays')url.searchParams.set('output','personal');return url.toString()}catch{return''}}
  function reconnectHref(){return'/auth/spmt/login?next='+encodeURIComponent(location.pathname+location.search)}
  function setActive(kind,id){state.activeKind=kind;state.activeId=String(id);if(panel)panel.hidden=false;renderPanel();renderTray()}
  function renderTray(){if(!tray)return;const current=slots();tray.querySelector('.spmt-status-dot').classList.toggle('connected',state.connected);tray.querySelector('.spmt-workspace-main').title=state.connected?'Open canonical SPMT workspace':'Reconnect SPMT workspace';const slotBox=tray.querySelector('.spmt-slots');slotBox.innerHTML='';current.forEach(slot=>{const b=document.createElement('button');b.type='button';b.className='spmt-slot'+(panel&&!panel.hidden&&state.activeKind==='slot'&&Number(state.activeId)===Number(slot.id)?' active':'');b.innerHTML='<strong>'+escapeHtml(slot.title||('Slot '+slot.id))+'</strong><small>'+(state.connected?(slot.collapsed?'Hidden':'Slot '+slot.id):'SPMT offline')+'</small>';b.addEventListener('click',()=>state.connected?setActive('slot',slot.id):location.assign(reconnectHref()));slotBox.append(b)});const reconnect=tray.querySelector('[data-reconnect]');if(reconnect){reconnect.hidden=state.connected;reconnect.onclick=()=>{location.href=reconnectHref()}}const personal=tray.querySelector('[data-personal-toggle]');if(personal){personal.textContent='Personal '+(state.personalVisible?'On':'Off');personal.setAttribute('aria-pressed',state.personalVisible?'true':'false')}}
  function addTab(tabs,label,kind,id){const b=document.createElement('button');b.type='button';b.className=state.activeKind===kind&&String(state.activeId)===String(id)?'active':'';b.textContent=label;b.addEventListener('click',()=>setActive(kind,id));tabs.append(b)}
  function renderPanel(){if(!panel)return;const tabs=panel.querySelector('.spmt-workspace-tabs');tabs.innerHTML='';slots().forEach(slot=>addTab(tabs,slot.title||('Slot '+slot.id),'slot',slot.id));[['Workspace','worktray'],['Overlay Bay','overlays'],['Settings','settings']].forEach(([label,id])=>{if(surface(id))addTab(tabs,label,'surface',id)});if(!state.connected){frame.hidden=true;empty.hidden=false;empty.innerHTML='<div><strong>SPMT workspace disconnected.</strong><br>Reconnect once to restore shared slots, surfaces, and Personal overlay.</div>';return}let target='';if(state.activeKind==='slot'){const active=slots().find(s=>Number(s.id)===Number(state.activeId));target=String(active&&active.url||'').trim()}else{target=surfaceUrl(state.activeId)}if(target){empty.hidden=true;frame.hidden=false;if(frame.src!==target)frame.src=target}else{frame.hidden=true;frame.removeAttribute('src');empty.hidden=false;empty.innerHTML='<div>The selected canonical workspace surface is not currently available.</div>'}}
  function renderOverlay(){if(!overlayLayer)return;overlayLayer.innerHTML='';if(!state.connected||!state.personalVisible||!state.personalOverlayUrl)return;const f=document.createElement('iframe');f.src=state.personalOverlayUrl;f.title='SPMT Personal overlay';f.allow='autoplay; microphone; camera; fullscreen; clipboard-write';f.setAttribute('data-canonical-personal-overlay','true');overlayLayer.append(f)}
  function togglePersonal(){state.personalVisible=!state.personalVisible;try{localStorage.setItem(VISIBILITY_KEY,state.personalVisible?'1':'0')}catch{}renderOverlay();renderTray()}
  function escapeHtml(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
  function mount(){if(document.getElementById('spmt-workspace-tray'))return;starLayer=document.createElement('div');starLayer.className='spmt-star-layer';starLayer.setAttribute('aria-hidden','true');overlayLayer=document.createElement('div');overlayLayer.className='spmt-runtime-overlay';overlayLayer.setAttribute('aria-label','Canonical SPMT Personal overlay');panel=document.createElement('section');panel.className='spmt-workspace-panel';panel.hidden=true;panel.innerHTML='<div class="spmt-workspace-bar"><div class="spmt-workspace-tabs"></div><button class="spmt-workspace-close" type="button">Close</button></div><iframe class="spmt-workspace-frame" title="SPMT Workspace surface" allow="autoplay; microphone; camera; fullscreen; clipboard-write"></iframe><div class="spmt-workspace-empty" hidden></div>';frame=panel.querySelector('iframe');empty=panel.querySelector('.spmt-workspace-empty');tray=document.createElement('aside');tray.id='spmt-workspace-tray';tray.className='spmt-workspace-tray';tray.setAttribute('aria-label','SPMT workspace tray');tray.innerHTML='<button class="spmt-workspace-main" type="button">'+icon('worktray')+'<span class="label">Workspace</span><i class="spmt-status-dot"></i></button><div class="spmt-slots"></div><div class="spmt-manage"><button type="button" data-surface="overlays" title="Open canonical Overlay Bay">'+icon('overlay')+'</button><button type="button" data-surface="settings" title="Open canonical Settings">'+icon('settings')+'</button><button type="button" class="spmt-personal-toggle" data-personal-toggle aria-pressed="true" title="Toggle Personal overlay">Personal On</button><button type="button" data-reconnect title="Reconnect SPMT" hidden>↻</button></div>';document.body.append(starLayer,overlayLayer,panel,tray);tray.querySelector('.spmt-workspace-main').addEventListener('click',()=>{if(!state.connected){location.href=reconnectHref();return}if(!panel.hidden&&state.activeKind==='surface'&&state.activeId==='worktray'){panel.hidden=true;renderTray();return}setActive('surface','worktray')});tray.querySelectorAll('[data-surface]').forEach(button=>button.addEventListener('click',()=>state.connected?setActive('surface',button.dataset.surface):location.assign(reconnectHref())));tray.querySelector('[data-personal-toggle]').addEventListener('click',togglePersonal);panel.querySelector('.spmt-workspace-close').addEventListener('click',()=>{panel.hidden=true;renderTray()});renderStars(70);renderTray()}
  async function refresh(){try{const r=await fetch(PROFILE_ENDPOINT,{credentials:'include',cache:'no-store',headers:{accept:'application/json'}});if(!r.ok){state.connected=false;state.profile=null;state.surfaces=[];state.personalOverlayUrl='';renderTray();renderPanel();renderOverlay();return}const data=await r.json();const profile=profileFrom(data);const canonical=canonicalFrom(data);if(!profile){state.connected=false;state.profile=null;state.surfaces=[];state.personalOverlayUrl='';renderTray();renderPanel();renderOverlay();return}state.connected=true;state.profile=profile;state.origin=String(canonical.origin||'');state.surfaces=Array.isArray(canonical.surfaces)?canonical.surfaces:[];state.outputs=canonical.outputs&&typeof canonical.outputs==='object'?canonical.outputs:{public:'',personal:''};state.personalOverlayUrl=String(data&&data.shared&&data.shared.personalOverlayUrl||canonical.outputs&&canonical.outputs.personal||'');apply(profile);renderTray();renderPanel();renderOverlay()}catch{state.connected=false;renderTray();renderPanel();renderOverlay()}}
  mount();refresh();
  window.setInterval(refresh,30000);window.addEventListener('focus',refresh);document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh()});window.addEventListener('message',e=>{if(!e.data||e.data.type!=='spmt.surface.updated')return;let expected='';try{expected=new URL(state.origin).origin}catch{}if(expected&&e.origin!==expected)return;refresh()});
})();
</script>`;
}
