export function spmtSharedUiHead(appId: string): string {
  const safeApp = JSON.stringify(appId).slice(1, -1);
  return `<style id="spmt-shared-shell-style">
:root{--spmt-bg:#080b14;--spmt-surface:#171321;--spmt-surface-rgb:23,19,33;--spmt-text:#f8fafc;--spmt-accent:#ff8a3d;--spmt-accent-rgb:255,138,61;--spmt-radius:18px;--spmt-glass:.65;--spmt-blur:22px;--spmt-border:.15;--spmt-stars:.7;--spmt-nebula:.8;--spmt-glow:.8;--spmt-density:1;--spmt-motion:1}
html[data-spmt-theme]{background:var(--spmt-bg);color:var(--spmt-text)}
body.spmt-host-shell{background:var(--spmt-bg)!important;color:var(--spmt-text)!important;position:relative;isolation:isolate;padding-bottom:76px!important}
.spmt-star-layer{position:fixed;inset:0;z-index:-2;pointer-events:none;overflow:hidden;opacity:var(--spmt-stars)}
.spmt-star{position:absolute;width:2px;height:2px;border-radius:999px;background:#fff;box-shadow:0 0 5px rgba(255,255,255,.65)}
body.spmt-host-shell:after{content:"";position:fixed;inset:0;pointer-events:none;z-index:-1;background:radial-gradient(circle at 10% 0%,rgba(var(--spmt-accent-rgb),calc(.25 * var(--spmt-nebula))),transparent 36rem),radial-gradient(circle at 92% 86%,rgba(var(--spmt-accent-rgb),calc(.12 * var(--spmt-nebula))),transparent 34rem),linear-gradient(180deg,var(--spmt-bg),#03050a 92%)}
body.spmt-host-shell :is(.panel,.card,.hero,.status,.topbar,.toolbar,.workspace-card,.surface,.box){border-color:rgba(255,255,255,var(--spmt-border))!important;border-radius:var(--spmt-radius)!important;backdrop-filter:blur(var(--spmt-blur))!important;-webkit-backdrop-filter:blur(var(--spmt-blur))!important}
body.spmt-host-shell :is(.panel,.card,.hero,.status,.workspace-card,.surface,.box){background:rgba(var(--spmt-surface-rgb),calc(var(--spmt-glass) * .72))!important}
body.spmt-host-shell :is(.button.primary,button:not(.secondary):not(.ghost),.primary){background:linear-gradient(135deg,var(--spmt-accent),rgba(var(--spmt-accent-rgb),.62))!important}
body.spmt-host-shell .eyebrow{color:var(--spmt-accent)!important}
body.spmt-host-shell .shell{padding-top:calc(24px * var(--spmt-density))!important}
body.spmt-host-shell.spmt-no-motion *,body.spmt-host-shell.spmt-no-motion *:before,body.spmt-host-shell.spmt-no-motion *:after{scroll-behavior:auto!important;transition:none!important;animation:none!important}
.spmt-runtime-overlay{position:fixed;inset:0;z-index:10010;pointer-events:none;overflow:hidden}.spmt-runtime-overlay iframe{position:absolute;border:0;background:transparent}
.spmt-workspace-panel{position:fixed;left:50%;bottom:84px;transform:translateX(-50%);z-index:10030;width:min(980px,calc(100vw - 36px));height:min(72vh,700px);display:grid;grid-template-rows:auto minmax(0,1fr);overflow:hidden;border:1px solid rgba(255,255,255,.15);border-radius:calc(var(--spmt-radius) + 4px);background:rgba(3,5,10,.92);box-shadow:0 28px 90px rgba(0,0,0,.62);backdrop-filter:blur(24px)}
.spmt-workspace-panel[hidden]{display:none!important}.spmt-workspace-bar{display:flex;align-items:center;gap:8px;padding:9px;border-bottom:1px solid rgba(255,255,255,.1);background:rgba(255,255,255,.025)}.spmt-workspace-tabs{display:flex;min-width:0;flex:1;gap:7px;flex-wrap:wrap}.spmt-workspace-tabs button,.spmt-workspace-close{display:inline-flex;align-items:center;gap:7px;border:1px solid rgba(255,255,255,.1);border-radius:10px;padding:8px 10px;background:rgba(255,255,255,.035);color:#d4d4d8;font:750 12px Inter,ui-sans-serif,system-ui,sans-serif;cursor:pointer}.spmt-workspace-tabs button.active{border-color:rgba(var(--spmt-accent-rgb),.62);background:rgba(var(--spmt-accent-rgb),.14);color:#fff}.spmt-workspace-close{margin-left:auto}.spmt-workspace-frame{width:100%;height:100%;border:0;background:transparent}.spmt-workspace-empty{display:grid;place-items:center;padding:28px;text-align:center;color:#a1a1aa;font:600 13px/1.5 Inter,ui-sans-serif,system-ui,sans-serif}.spmt-workspace-empty a{display:inline-block;margin-top:12px;color:#fff;text-decoration:none;border:1px solid rgba(255,255,255,.14);border-radius:10px;padding:8px 12px;background:rgba(255,255,255,.07)}
.spmt-workspace-tray{position:fixed;left:50%;bottom:12px;transform:translateX(-50%);z-index:10040;width:min(980px,calc(100vw - 36px));display:flex;align-items:center;gap:8px;min-height:58px;padding:8px;border:1px solid rgba(255,255,255,.15);border-radius:calc(var(--spmt-radius) + 2px);background:rgba(3,5,10,.82);box-shadow:0 -14px 42px rgba(0,0,0,.45),0 0 calc(28px * var(--spmt-glow)) rgba(var(--spmt-accent-rgb),.12);backdrop-filter:blur(20px)}
.spmt-workspace-main,.spmt-slot,.spmt-manage a{border:1px solid rgba(255,255,255,.1);background:rgba(255,255,255,.035);color:#fff;border-radius:11px;cursor:pointer;font-family:Inter,ui-sans-serif,system-ui,sans-serif}.spmt-workspace-main{display:inline-flex;align-items:center;gap:8px;min-height:40px;padding:0 12px;font-size:12px;font-weight:800}.spmt-workspace-main svg,.spmt-manage svg{width:16px;height:16px;fill:none;stroke:currentColor;stroke-width:1.8;stroke-linecap:round;stroke-linejoin:round}.spmt-status-dot{width:7px;height:7px;border-radius:999px;background:#fbbf24}.spmt-status-dot.connected{background:#34d399}.spmt-slots{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:7px;min-width:0;flex:1}.spmt-slot{min-width:0;padding:7px 10px;text-align:left}.spmt-slot strong,.spmt-slot small{display:block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.spmt-slot strong{font-size:11px}.spmt-slot small{margin-top:3px;color:#71717a;font-size:9px;text-transform:uppercase;letter-spacing:.08em}.spmt-slot.active{border-color:rgba(var(--spmt-accent-rgb),.55);background:rgba(var(--spmt-accent-rgb),.12)}.spmt-manage{display:flex;gap:5px}.spmt-manage a{display:grid;place-items:center;width:38px;height:38px;text-decoration:none;color:#d4d4d8}.spmt-manage a:hover{color:#fff;background:rgba(255,255,255,.08)}
@media(max-width:720px){body.spmt-host-shell{padding-bottom:70px!important}.spmt-workspace-panel{inset:10px 10px 78px 10px;transform:none;width:auto;height:auto}.spmt-workspace-tray{bottom:8px;width:calc(100vw - 16px)}.spmt-workspace-main span.label,.spmt-manage{display:none}.spmt-slot{padding:7px}.spmt-slot small{display:none}}
@media(prefers-reduced-motion:reduce){body.spmt-host-shell *,body.spmt-host-shell *:before,body.spmt-host-shell *:after{scroll-behavior:auto!important;transition:none!important;animation:none!important}}
</style><meta name="spmt-host-app" content="${safeApp}">`;
}

export function spmtSharedUiScript(appId: string, profileEndpoint = "/athena/api/settings"): string {
  const encodedApp = JSON.stringify(appId);
  const encodedProfileEndpoint = JSON.stringify(profileEndpoint);
  return `<script id="spmt-shared-shell-script">
(()=>{
  const APP=${encodedApp};
  const PROFILE_ENDPOINT=${encodedProfileEndpoint};
  const SPACEMOUNTAIN='https://spacemountain.live';
  const palettes={
    'solar-flare':{bg:'#080b14',surface:'#171321',text:'#f8fafc',accent:'#ff8a3d'},
    'nebula-purple':{bg:'#090712',surface:'#1d1530',text:'#f8f4ff',accent:'#a855f7'},
    'oceanic-blue':{bg:'#06111a',surface:'#0c2535',text:'#effaff',accent:'#22d3ee'},
    'aurora-green':{bg:'#07110d',surface:'#10291e',text:'#f0fdf4',accent:'#34d399'}
  };
  const root=document.documentElement;
  const state={connected:false,profile:null,overlay:null,activeSlotId:null};
  let starLayer=null,tray=null,panel=null,frame=null,empty=null,overlayLayer=null;
  document.body.classList.add('spmt-host-shell');
  function rgb(hex){const v=String(hex||'').replace('#','');if(!/^[0-9a-f]{6}$/i.test(v))return'255,138,61';return parseInt(v.slice(0,2),16)+','+parseInt(v.slice(2,4),16)+','+parseInt(v.slice(4,6),16)}
  function radius(v){return({sm:'12px',md:'18px',lg:'26px',full:'999px'})[v]||'18px'}
  function profileFrom(data){return data&&data.shared&&data.shared.profile||data&&data.workspace&&data.workspace.profile||data&&data.profile||null}
  function overlayFrom(data){return data&&data.shared&&data.shared.overlayWorkspace||data&&data.overlayWorkspace||null}
  function apply(profile){
    const a=profile&&profile.appearance;if(!a)return;
    const mapping=String((profile.appThemeMappings||{})[APP]||'follow-workspace');
    const themeId=mapping==='follow-workspace'?a.themeId:mapping;
    const p=palettes[themeId]||palettes['solar-flare'];
    const accent=a.accentColor||p.accent;
    root.dataset.spmtTheme=themeId;
    root.style.setProperty('--spmt-bg',p.bg);root.style.setProperty('--spmt-surface',p.surface);root.style.setProperty('--spmt-surface-rgb',rgb(p.surface));root.style.setProperty('--spmt-text',p.text);root.style.setProperty('--spmt-accent',accent);root.style.setProperty('--spmt-accent-rgb',rgb(accent));
    root.style.setProperty('--spmt-radius',radius(a.cornerRadius));root.style.setProperty('--spmt-glass',String((a.glassOpacity??65)/100));root.style.setProperty('--spmt-blur',String(a.blurStrength??22)+'px');root.style.setProperty('--spmt-border',String(Math.max(.06,(a.borderStrength??60)/400)));root.style.setProperty('--spmt-stars',String((a.starDensity??70)/100));root.style.setProperty('--spmt-nebula',String((a.nebulaIntensity??80)/100));root.style.setProperty('--spmt-glow',String((a.glowIntensity??80)/100));root.style.setProperty('--spmt-density',a.density==='compact'?'.86':a.density==='spacious'?'1.15':'1');
    document.body.classList.toggle('spmt-no-motion',a.animation&&a.animation.enabled===false||a.accessibility&&a.accessibility.reduceMotion===true);
    renderStars(Number(a.starDensity??70));
  }
  function icon(kind){return kind==='settings'?'<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="3"/><path d="M19 13.5v-3l-2-.6a7 7 0 0 0-.7-1.7l1-1.8-2.1-2.1-1.8 1a7 7 0 0 0-1.7-.7L11 2H8l-.6 2a7 7 0 0 0-1.7.7l-1.8-1L1.8 5.8l1 1.8a7 7 0 0 0-.7 1.7L0 10v3l2 .6a7 7 0 0 0 .7 1.7l-1 1.8 2.1 2.1 1.8-1a7 7 0 0 0 1.7.7L8 21h3l.6-2a7 7 0 0 0 1.7-.7l1.8 1 2.1-2.1-1-1.8a7 7 0 0 0 .7-1.7z"/></svg>':kind==='overlay'?'<svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="3"/><path d="M8 8h8v8H8z"/></svg>':'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 5h16v4H4zM4 11h7v8H4zM13 11h7v8h-7z"/></svg>'}
  function renderStars(density){if(!starLayer)return;starLayer.innerHTML='';const count=Math.max(8,Math.min(90,Math.round(Number(density||70)*.75)));for(let i=0;i<count;i+=1){const star=document.createElement('i');star.className='spmt-star';star.style.left=String((i*73+17)%997/10)+'%';star.style.top=String((i*131+29)%991/10)+'%';const size=1+((i*17)%3);star.style.width=size+'px';star.style.height=size+'px';star.style.opacity=String(.32+((i*31)%60)/100);starLayer.append(star)}}
  function slots(){const raw=Array.isArray(state.profile&&state.profile.dockSlots)?state.profile.dockSlots:[];return[1,2,3].map(id=>raw.find(s=>Number(s&&s.id)===id)||{id:id,title:'Slot '+id,url:'',collapsed:true})}
  function reconnectHref(){return'/auth/spmt/login?next='+encodeURIComponent(location.pathname+location.search)}
  function renderTray(){if(!tray)return;const current=slots();tray.querySelector('.spmt-status-dot').classList.toggle('connected',state.connected);tray.querySelector('.spmt-workspace-main').title=state.connected?'SPMT workspace connected':'Reconnect SPMT workspace';const slotBox=tray.querySelector('.spmt-slots');slotBox.innerHTML='';current.forEach(slot=>{const b=document.createElement('button');b.type='button';b.className='spmt-slot'+(panel&&!panel.hidden&&Number(state.activeSlotId)===Number(slot.id)?' active':'');b.innerHTML='<strong>'+escapeHtml(slot.title||('Slot '+slot.id))+'</strong><small>'+(state.connected?(slot.collapsed?'Hidden':'Slot '+slot.id):'SPMT offline')+'</small>';b.addEventListener('click',()=>openSlot(slot));slotBox.append(b)});const reconnect=tray.querySelector('[data-reconnect]');reconnect.hidden=state.connected;reconnect.href=reconnectHref()}
  function renderPanel(){if(!panel)return;const tabs=panel.querySelector('.spmt-workspace-tabs');tabs.innerHTML='';slots().forEach(slot=>{const b=document.createElement('button');b.type='button';b.className=Number(state.activeSlotId)===Number(slot.id)?'active':'';b.textContent=slot.title||('Slot '+slot.id);b.addEventListener('click',()=>openSlot(slot));tabs.append(b)});const active=slots().find(s=>Number(s.id)===Number(state.activeSlotId))||slots()[0];if(!state.connected){frame.hidden=true;empty.hidden=false;empty.innerHTML='<div><strong>SPMT workspace disconnected.</strong><br>Reconnect once to restore shared slots and overlays.<br><a href="'+escapeAttr(reconnectHref())+'">Reconnect SPMT</a></div>';return}if(active&&String(active.url||'').trim()){empty.hidden=true;frame.hidden=false;if(frame.src!==active.url)frame.src=active.url}else{frame.hidden=true;empty.hidden=false;empty.innerHTML='<div>This workspace slot has no URL assigned.<br><a href="'+SPACEMOUNTAIN+'/?surface=workspace" target="_blank" rel="noreferrer">Manage Workspace in SpaceMountain</a></div>'}}
  function renderOverlay(){if(!overlayLayer)return;overlayLayer.innerHTML='';const overlay=state.overlay;if(!state.connected||!overlay||overlay.enabled===false)return;const widgets=Array.isArray(overlay.widgets)?overlay.widgets:[];widgets.filter(w=>w&&w.visible!==false&&w.url).forEach(w=>{const f=document.createElement('iframe');f.src=String(w.url);f.title=String(w.title||w.id||'SPMT overlay');f.allow='autoplay; microphone; camera; fullscreen; clipboard-write';f.style.left=Number(w.x||0)+'%';f.style.top=Number(w.y||0)+'%';f.style.width=Number(w.width||320)+'px';f.style.height=Number(w.height||180)+'px';const o=Number(w.opacity??1);f.style.opacity=String(Math.max(0,Math.min(1,o>1?o/100:o)));f.style.pointerEvents=w.interactive?'auto':'none';overlayLayer.append(f)})}
  function openSlot(slot){state.activeSlotId=Number(slot&&slot.id)||1;if(panel)panel.hidden=false;renderPanel();renderTray()}
  function escapeHtml(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
  function escapeAttr(value){return escapeHtml(value)}
  function mount(){if(document.getElementById('spmt-workspace-tray'))return;starLayer=document.createElement('div');starLayer.className='spmt-star-layer';starLayer.setAttribute('aria-hidden','true');overlayLayer=document.createElement('div');overlayLayer.className='spmt-runtime-overlay';overlayLayer.setAttribute('aria-hidden','true');panel=document.createElement('section');panel.className='spmt-workspace-panel';panel.hidden=true;panel.innerHTML='<div class="spmt-workspace-bar"><div class="spmt-workspace-tabs"></div><button class="spmt-workspace-close" type="button">Close</button></div><iframe class="spmt-workspace-frame" title="SPMT Workspace slot" allow="autoplay; microphone; camera; fullscreen; clipboard-write"></iframe><div class="spmt-workspace-empty" hidden></div>';frame=panel.querySelector('iframe');empty=panel.querySelector('.spmt-workspace-empty');tray=document.createElement('aside');tray.id='spmt-workspace-tray';tray.className='spmt-workspace-tray';tray.setAttribute('aria-label','SPMT workspace tray');tray.innerHTML='<button class="spmt-workspace-main" type="button">'+icon('worktray')+'<span class="label">Workspace</span><i class="spmt-status-dot"></i></button><div class="spmt-slots"></div><div class="spmt-manage"><a href="'+SPACEMOUNTAIN+'/?surface=workspace" target="_blank" rel="noreferrer" title="Manage Workspace">'+icon('worktray')+'</a><a href="'+SPACEMOUNTAIN+'/?surface=overlay" target="_blank" rel="noreferrer" title="Manage Overlay">'+icon('overlay')+'</a><a href="'+SPACEMOUNTAIN+'/settings" target="_blank" rel="noreferrer" title="Manage Settings">'+icon('settings')+'</a><a data-reconnect href="'+escapeAttr(reconnectHref())+'" title="Reconnect SPMT" hidden>↻</a></div>';document.body.append(starLayer,overlayLayer,panel,tray);tray.querySelector('.spmt-workspace-main').addEventListener('click',()=>{if(!state.connected){location.href=reconnectHref();return}panel.hidden=!panel.hidden;if(!panel.hidden&&state.activeSlotId==null)state.activeSlotId=slots()[0].id;renderPanel();renderTray()});panel.querySelector('.spmt-workspace-close').addEventListener('click',()=>{panel.hidden=true;renderTray()});renderStars(70);renderTray()}
  async function refresh(){try{const r=await fetch(PROFILE_ENDPOINT,{credentials:'include',cache:'no-store',headers:{accept:'application/json'}});if(!r.ok){state.connected=false;state.profile=null;state.overlay=null;renderTray();renderPanel();renderOverlay();return}const data=await r.json();const profile=profileFrom(data);if(!profile){state.connected=false;state.profile=null;state.overlay=null;renderTray();renderPanel();renderOverlay();return}state.connected=true;state.profile=profile;state.overlay=overlayFrom(data);if(state.activeSlotId==null)state.activeSlotId=slots()[0].id;apply(profile);renderTray();renderPanel();renderOverlay()}catch{state.connected=false;renderTray();renderPanel();renderOverlay()}}
  mount();refresh();
  window.setInterval(refresh,30000);window.addEventListener('focus',refresh);document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh()});window.addEventListener('message',e=>{if(e.origin!=='https://spmt.live'||e.data&&e.data.type!=='spmt.surface.updated')return;refresh()});
})();
</script>`;
}
